image: openjdk:11-jdk-slim

stages:
  - build
  - deploy_aws_dev


before_script:
  - chmod +x mvnw

cache:
  paths:
    - .m2/repository

build:
  stage: build
  script: ./mvnw package
  artifacts:
    paths:
      - target/backend-api-0.0.1-SNAPSHOT.war

variables:
  SONAR_TOKEN: "0b9bff237ae73e371877d117e3cbfeccbeb18861"
  SONAR_HOST_URL: "http://ec2-3-236-113-61.compute-1.amazonaws.com"
  GIT_DEPTH: 0

variables:
  AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
  AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
  AWS_REGION: $AWS_DEFAULT_REGION

deploy_aws_dev:
  image: python:latest
  stage: deploy_aws_dev
  only: 
    - master
  script:
    - pip install awscli
    - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
    - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
    - aws configure set region $AWS_DEFAULT_REGION
    - aws s3 cp target/backend-api-0.0.1-SNAPSHOT.war s3://elasticbeanstalk-us-east-1-079361136472/backend-api-$CI_PIPELINE_ID.war
    - aws elasticbeanstalk create-application-version --application-name SM2-Backend-API --version-label backend-api-$CI_PIPELINE_ID --source-bundle S3Bucket=elasticbeanstalk-us-east-1-079361136472,S3Key=backend-api-$CI_PIPELINE_ID.war
    - aws elasticbeanstalk update-environment --application-name SM2-Backend-API --environment-name Env-Sm2BackendApi --version-label backend-api-$CI_PIPELINE_ID
